version: '3.1'
services:
  stats-server:
    build: stats/stats-server
    image: stats-server-image
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot

  stats-db:
    image: postgres:16.1
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot

  ewm-service:
    build: ewm-service
    image: ewm-main-image
    container_name: ewm-main
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - SPRING_DATASOURCE_EWM_URL=jdbc:postgresql://ewm-db:5432/ewm-db
      - STATS_SERVER_URL=http://stats-server:9090
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot

  ewm-db:
    image: postgres:16.1
    container_name: ewm-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot