DROP TABLE IF EXISTS hits CASCADE;
CREATE TABLE IF NOT EXISTS hits
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    app        VARCHAR,
    uri        VARCHAR,
    ip         VARCHAR,
    timestamp TIMESTAMP WITH TIME ZONE
                             );